#!/bin/bash

[[ -z $RDM_PATH ]] && RDM_PATH='/Applications'

read -p "Install RDM to ${RDM_PATH}? (Y/n): " __doInstall

while [[ -z $__flag ]]; do
    case "$__doInstall" in
        [Yy]*|'')
            __flag=true
            ;;
        [Nn]*   )
            exit 1
            ;;
        *       )
            read -p "Please type y or n: " __doInstall
            ;;
    esac
done

osascript -e 'quit app "RDM"'
__tempdir=$(mktemp -d) 2>&1 > /dev/null
__ERR_LOG="
$(xcodebuild -archivePath "${__tempdir}/RDM" -scheme RDM archive 2>&1 > /dev/null)
$(xcodebuild -exportArchive -archivePath "${__tempdir}/RDM.xcarchive" -exportPath "$RDM_PATH" -exportOptionsPlist etc/export.plist 2>&1 > /dev/null)"

if [[ $? = 0 ]]; then
    rm -rf "$__tempdir" &>/dev/null
    open "${RDM_PATH}/RDM.app"
    echo "Build finished!"
else
    echo "
An error occured; try again
${__ERR_LOG}"
    exit 100
fi
